In [1]:
import pandas as pd

In [2]:
campanas_df = pd.read_csv(r"..\01_datos\processed\campanas.csv")
conversiones_df = pd.read_csv(r"..\01_datos\processed\conversiones.csv")
transacciones_df = pd.read_csv(r"..\01_datos\processed\transacciones.csv")

In [3]:
campanas_df

,fecha,campana_id,canal,tipo_campana,objetivo,audiencia,impresiones,clics,ctr,cpc_mxn,gasto_mxn,conversiones,valor_conv_mxn,roas,dia_semana
0,2024-11-10,FB-AWA-002,Meta,Awareness,Alcance,Lookalike 1% compradores anteriores,6267,85,0.01356,5.45,467.15,0,0.00,0.00,Sunday
1,2024-06-18,GG-SRC-003,Google,Search,Clics,Intención: como perder peso en casa,412,36,0.08723,19.36,707.76,2,1256.68,1.78,Tuesday
2,2024-05-26,GG-DSP-001,Google,Display,Impresiones,Afinidad: bienestar y fitness,14286,179,0.01253,3.27,586.70,2,1465.95,2.50,Sunday
3,2024-04-04,FB-CVR-001,Meta,Conversion,Compras,Retargeting carrito abandonado,2601,169,0.06496,9.85,1666.62,9,7784.51,4.67,Thursday
4,2024-02-12,FB-CON-002,Meta,Consideracion,Trafico,"Intereses: yoga, meditacion, fitness",3376,132,0.03909,7.17,949.99,4,2596.36,2.73,Monday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4253,2024-10-11,FB-AWA-002,Meta,Awareness,Alcance,Lookalike 1% compradores anteriores,10929,137,0.01253,4.23,580.60,0,0.00,0.00,Friday
4254,2024-04-07,GG-DSP-001,Google,Display,Impresiones,Afinidad: bienestar y fitness,14161,160,0.01130,2.95,474.60,1,909.91,1.92,Sunday
4255,2024-08-03,GG-SRC-003,Google,Search,Clics,Intención: como perder peso en casa,312,19,0.06084,19.21,379.52,0,0.00,0.00,Saturday
4256,2024-11-02,GG-DSP-001,Google,Display,Impresiones,Afinidad: bienestar y fitness,19312,113,0.00585,3.57,405.64,0,0.00,0.00,Saturday
4257,2024-08-08,GG-DSP-001,Google,Display,Impresiones,Afinidad: bienestar y fitness,18342,98,0.00534,3.51,347.29,0,0.00,0.00,Thursday

In [4]:
campanas_df = campanas_df.rename(columns={'gasto_mxn': 'gastos', 'valor_conv_mxn': 'valor_conv'})
metricas = ['impresiones', 'clics', 'conversiones', 'gastos', 'valor_conv']

In [5]:
canal_df = campanas_df.groupby(['canal'])[metricas].sum().reset_index()

canal_df['CTR'] = ((canal_df['clics'] / canal_df['impresiones'])*100).fillna(0).round(1)
canal_df['CVR'] = ((canal_df['conversiones'] / canal_df['clics'])*100).fillna(0).round(1)
canal_df['CAC'] = (canal_df['gastos'] / canal_df['conversiones']).fillna(0).round(1)
canal_df['ROAS'] = (canal_df['valor_conv'] / canal_df['gastos']).fillna(0).round(1)
canal_df['CPM'] = (canal_df['gastos'] / canal_df['impresiones'] * 1000).fillna(0).round(1)

canal_df = canal_df[['canal', 'ROAS', 'CAC', 'CPM', 'CTR', 'CVR']]

canal_df

    canal  ROAS    CAC    CPM  CTR  CVR
0  Google   1.5  447.2  101.5  1.5  1.6
1    Meta   2.2  295.0  165.8  2.3  2.4

In [6]:
tipo_campana_df = campanas_df.groupby(['tipo_campana', 'canal'])[metricas].sum().reset_index()

tipo_campana_df['CTR'] = ((tipo_campana_df['clics'] / tipo_campana_df['impresiones'])*100).fillna(0).round(1)
tipo_campana_df['CVR'] = ((tipo_campana_df['conversiones'] / tipo_campana_df['clics'])*100).fillna(0).round(1)
tipo_campana_df['CAC'] = (tipo_campana_df['gastos'] / tipo_campana_df['conversiones']).fillna(0).round(1)
tipo_campana_df['ROAS'] = (tipo_campana_df['valor_conv'] / tipo_campana_df['gastos']).fillna(0).round(1)
tipo_campana_df['CPM'] = (tipo_campana_df['gastos'] / tipo_campana_df['impresiones'] * 1000).fillna(0).round(1)
tipo_campana_df['Inversion'] = (tipo_campana_df['gastos']).fillna(0).round(1)

tipo_campana_df = tipo_campana_df[['tipo_campana', 'canal', 'Inversion', 'ROAS', 'CAC', 'CPM', 'CTR', 'CVR']]

tipo_campana_df

    tipo_campana   canal  Inversion  ROAS     CAC     CPM  CTR  CVR
0      Awareness    Meta   453005.1   0.5  1201.6    64.8  1.5  0.4
1  Consideracion    Meta   624806.5   2.2   312.1   211.1  3.1  2.2
2     Conversion    Meta   809911.0   3.2   201.5   566.1  4.7  5.9
3        Display  Google   392157.0   1.4   452.8    31.8  1.0  0.7
4         Search  Google   870665.7   1.5   433.0  1495.2  8.1  4.3
5        YouTube  Google   224076.6   1.3   500.2   130.8  2.4  1.1

In [9]:
campana_id_df = campanas_df.groupby(['campana_id', 'tipo_campana'])[metricas].sum().reset_index()

campana_id_df['CTR'] = ((campana_id_df['clics'] / campana_id_df['impresiones'])*100).fillna(0).round(1)
campana_id_df['CVR'] = ((campana_id_df['conversiones'] / campana_id_df['clics'])*100).fillna(0).round(1)
campana_id_df['CAC'] = (campana_id_df['gastos'] / campana_id_df['conversiones']).fillna(0).round(1)
campana_id_df['ROAS'] = (campana_id_df['valor_conv'] / campana_id_df['gastos']).fillna(0).round(1)
campana_id_df['CPM'] = (campana_id_df['gastos'] / campana_id_df['impresiones'] * 1000).fillna(0).round(1)
campana_id_df['CPC'] = (campana_id_df['gastos'] / campana_id_df['clics']).fillna(0).round(2)
campana_id_df['Inversion'] = (campana_id_df['gastos']).fillna(0).round(1)

campana_id_df = campana_id_df[['campana_id', 'tipo_campana', 'Inversion', 'ROAS', 'CAC', 'CPM', 'CTR', 'CPC', 'CVR']]

campana_id_df

,campana_id,tipo_campana,Inversion,ROAS,CAC,CPM,CTR,CPC,CVR
0,FB-AWA-001,Awareness,281237.1,0.6,1081.7,66.5,1.5,4.42,0.4
1,FB-AWA-002,Awareness,171768.0,0.4,1468.1,62.1,1.4,4.37,0.3
2,FB-CON-001,Consideracion,323935.0,2.2,311.8,208.9,3.1,6.68,2.1
3,FB-CON-002,Consideracion,300871.4,2.1,312.4,213.4,3.2,6.75,2.2
4,FB-CVR-001,Conversion,416958.4,3.2,198.8,557.9,4.7,11.86,6.0
5,FB-CVR-002,Conversion,392952.6,3.2,204.3,575.1,4.8,12.00,5.9
6,GG-DSP-001,Display,184400.1,1.4,462.2,32.0,1.0,3.16,0.7
7,GG-DSP-002,Display,207756.9,1.5,444.9,31.6,1.0,3.14,0.7
8,GG-SRC-001,Search,365841.7,1.6,410.1,1486.4,8.1,18.36,4.5
9,GG-SRC-002,Search,275186.2,1.5,443.8,1495.2,8.1,18.57,4.2
10,GG-SRC-003,Search,229637.7,1.4,460.2,1509.6,8.2,18.46,4.0
11,GG-YTB-001,YouTube,224076.6,1.3,500.2,130.8,2.4,5.42,1.1

In [8]:
audiencia_df = campanas_df[['audiencia', 'campana_id']].drop_duplicates().reset_index(drop=True)

audiencia_df

                                      audiencia  campana_id
0           Lookalike 1% compradores anteriores  FB-AWA-002
1           Intención: como perder peso en casa  GG-SRC-003
2                 Afinidad: bienestar y fitness  GG-DSP-001
3                Retargeting carrito abandonado  FB-CVR-001
4          Intereses: yoga, meditacion, fitness  FB-CON-002
5                Retargeting visitantes 30 días  FB-CON-001
6   Mujeres 25-40 CDMX interesadas en bienestar  FB-AWA-001
7                Canal: wellness, yoga, fitness  GG-YTB-001
8           Intención: cursos de yoga online MX  GG-SRC-001
9                  Remarketing sitio web 7 días  GG-DSP-002
10          Intención: meditacion guiada online  GG-SRC-002
11            Lookalike 3% suscriptores activos  FB-CVR-002